apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true

    # Broken in Grafana 8.x.x
    # basicAuth: true
    # secureJsonData:
    #   basicAuthUser: kp_resort_meteo
    #   basicAuthPassword: kp_resort_meteo
